name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue! Make sure you follow the code of conduct!'
        pr-message: 'Thank you for creating your first pull request! Make sure you follow the code of conduct!'
