name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This seems to be a stale issue, tagging as "no-issue-activity"'
        stale-pr-message: 'This seems to be a stale pull request, tagging as "no-pr-activity"'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
